name: Run ICC Rankings Script

on:
  schedule:
    - cron: "30 1 * * *"  # Runs at 1:30 AM UTC (7:00 AM IST) daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install System Dependencies (ODBC Driver for SQL Server)
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev odbcinst
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo add-apt-repository "$(curl -fsSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list)"
          sudo apt-get update
          sudo apt-get install -y msodbcsql17

      - name: Install Python Dependencies
        run: |
          pip install requests pandas pyodbc

      - name: Run Script
        run: python your_script.py
